[project]
name = 'day-4-task-management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.task-manager]
path = 'contracts/task-manager.clar'
clarity_version = 3
epoch = '3.1'

[contracts.user-profiles]
path = 'contracts/user-profiles.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
